### ISSUE TITLE
Switching from Single tick -> Multiple ticks erases history

### ISSUE THREAD

**Issue by DataStrategist** [lordi/tickmate#114]
I'm sure that it's because the var type is changing... but is it possible when switching from Single-tick to multiple all formerly ticked enties are converted to 1? Otherwise you lose the history.

Likewise, going from multiple -> binary should assign 0-> F and 1+ to T

**Comment by lordi** [comment]
Sorry for the late reply. Ideally you would be able to switch between single and multi tick all the time, so that your multi ticks are not forgotten when you switch to single and back.

**Comment by 0xDB** [comment]
@lordi Not sure when this was fixed, but I just tested it on Android 10 with the current version and it works. Changing from single tick to multiple ticks and back preserves both single tick entries and tick count.

**Comment by lordi** [comment]
Ok thx, closing this, please re-open if this is still happens on other OS versions with the latest Tickmate version
