### ISSUE TITLE
Add Ethereum (and other cryptocurrency) donation option(s)

### ISSUE THREAD

**Issue by refola** [lordi/tickmate#122]
Thanks for making Tickmate! It's an awesome app and I would like to donate to support its development. But I don't like BitCoin these days due to serious unresolved scalability issues leading to unpredictable and sometimes extremely high transaction fees. Please add addresses to donate via other cryptocurrencies like Ethereum. :-)

**Comment by lordi** [comment]
Thanks, best bug report I ever woke up to :-)
