### ISSUE TITLE
Change date format 

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [lordi/tickmate#124]
Hi,

I think  it would be great to allow for changing the date format that is displayed on the left of the main page. Especially to add "dd/mm/yy"  and "dd/mm"

Great app :D

**Comment by FliegendeWurst** [comment]
It should already respect the locale setting.

**Comment by Yendolosch** [comment]
+1 for the option to manually set a date format. I'm missing my ISO format...

**Comment by lordi** [comment]
Fixed by #147
If not, please re-open
