### ISSUE TITLE
user changes are lost on screen rotation 

### ISSUE THREAD

**Issue by ufarooq** [lordi/tickmate#130]
Open the app, go to track details, tap on the "2-weeks" icon to change and restart the activity by rotating, user inputs are lost and the app goes back to "2-weeks" trend.

**Comment by 0xDB** [comment]
@lordi Fixed in branch issue_130_keep_trend_on_rotation, would you like to review the changes before merge to master?

**Comment by lordi** [comment]
Looks good to me, you can go ahead and merge if tests are OK

**Comment by lordi** [comment]
Please make sure to update CHANGES.md

**Comment by lordi** [comment]
You can add a section "master" which we will then convert to the version number once we release it

**Comment by 0xDB** [comment]
Sorry, saw the 2 latter comments too late

**Comment by lordi** [comment]
Should be fixed in 1.4.8, please re-open if it still persists
