### ISSUE TITLE
Android 11 and backups to Android/data/

### ISSUE THREAD

**Issue by duelafn** [lordi/tickmate#131]
Hello, thanks for an excellent app!

Android 11 changed the storage permission and now forbids access to Android/data folders except fo an apps own private folder. Specifically, file manager apps no longer have access to Android/data/de.smasi.tickmate, even if the file manger has permission to access "All files". This means we can no longer usefully backup or export our ticks databases.

My dream is for a setting to customize the backup folder, but I'd be happy with a hard-coded location (e.g., storage:/Tickmate/) or even just a "share" or similar action if you want to preserve the permissionless nature of the app.

Thanks again!

----

Steps to reproduce:

- Select "backup database" → Ok
- Open any file manager, try to go to internal storage:Android/data/de.smasi.tickmate to access backup

What happens:

- File manager says Android/data is unavailable or empty (depending on the file manager app)

What should happen:

- tickmate saves to an accessible location

**Comment by lordi** [comment]
Hi thanks, unfortunately I don't have the time anymore to maintain this app. I'd be happy to accept pull requests, if anyone wants to implement this feature. It looks like this is much needed.

**Comment by lordi** [comment]
Should be closed via #132 
An updated version will be uploaded to Play store in the coming days.
Please re-open if the issue persists.
