### ISSUE TITLE
Migrate from travis CI to github actions?

### ISSUE THREAD

**Issue by lordi** [lordi/tickmate#133]
It might be simpler to run the gradle test script in github actions (see [travis config](https://github.com/lordi/tickmate/blob/master/.travis.yml))

**Comment by lordi** [comment]
@0xDB Is this something you can to look into?

**Comment by 0xDB** [comment]
I'll look into it!

**Comment by 0xDB** [comment]
I added the "Unit Tests" Github Action, which runs testDebugUnitTest on pull-request and push. You can view its first successful run in the Actions-tab. Hope it's ok that I added it directly to master, I did the testing on my forked repo first.

**Comment by lordi** [comment]
Awesome! I looked into the Actions output and it looks like its only building, not testing the app? Or am I missing something?

Yea for this its ok to push to master, in the future we should always check if CI is succesful before merging into master.

**Comment by lordi** [comment]
Ah nvm, it actually seems to run them but without test output. Cool, yea, I will try to make a signed new build and upload it within the next days.
