### ISSUE TITLE
Error showing numbers when opening Track Details and device language Arabic

### ISSUE THREAD

**Issue by AlbahrawyTiger** [lordi/tickmate#140]
![Track Details](https://user-images.githubusercontent.com/61330601/104368819-47b30e80-5525-11eb-8e3f-0aecea77c2d2.png)

**Comment by lordi** [comment]
Curious :thinking:

**Comment by AlbahrawyTiger** [comment]
> Curious 🤔

**Comment by AlbahrawyTiger** [comment]
> Curious 🤔

What do you mean?
