### ISSUE TITLE
A bug report of adaptation problem

### ISSUE THREAD

**Issue by yuhuitech** [lordi/tickmate#149]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the about page, **a part of text could not be seen clearly**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 1.4.13, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.

**Expected behavior**

I hope that I can see all of the texts on this page, and in this circumstance, part of them seem to be blocked, which I have drawn a red box around.

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.click the navigation button (3 vertical dots) on the right top corner of the main page, and then click "about ticktime" button
3.this error could be seen

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/128632726-8ea54358-8c4c-4d0a-a319-df9eee7e34b7.png" alt="Screenshot_1628427148 copy" width="250"/>

**Environment**

1. Version of tickmate : 1.4.13
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by lordi** [comment]
Fixed by #150 . Thanks!
