### ISSUE TITLE
Increase targetSdkVersion to 30+

### ISSUE THREAD

**Issue by grrrrr** [lordi/tickmate#163]
Starting 1st November 2022, any app that does not have a `targetSdkVersion` of at least `30` will not be discoverable or install-able from Google Play Store on new devices.

https://support.google.com/googleplay/android-developer/answer/11926878

The current `targetSdkVersion` of Tickmate is [29](https://github.com/lordi/tickmate/blob/9ac46e7168dce22ea4b63cf8f1b291b34ccba11f/app/build.gradle#L17)

It would be useful to get a maintenance release to at least allow continued installation on new devices.

**Comment by lordi** [comment]
Thanks for the notice. I'll try to find some time to do the release...

**Comment by grrrrr** [comment]
Thanks @lordi , nice to see tickmate getting some updates
