### ISSUE TITLE
Add a notification to remind the user to update ticks

### ISSUE THREAD

**Issue by jm-github** [lordi/tickmate#24]
hello,
Nice app I started to use, but I failed to update my bits every day.
It would be nice to add a simple notification to remind to fill the bits, if no bits are set since 48h for example

**Comment by blausand** [comment]
+1 for this feature. Combination with widget would be appreciated. 
(And a changelog in F-Droid link list :)

**Comment by lordi** [comment]
Currently working on this in branch [feature-notifications](https://github.com/lordi/tickmate/tree/feature-notifications)

**Comment by Lee-Carre** [comment]
RFE: multiple reminders, at user-configurable hours.

See the Daily Dozen app for a working example that's both usable & granular.

Consider that some activities are morning-only, and some evening-only.

Further; some are weekday-only, others weekend-only.
