### ISSUE TITLE
[feature] different colored ticks

### ISSUE THREAD

**Issue by grrrrr** [lordi/tickmate#26]
Could it be possible to allow the setting of unique colors for individual tracks?

I would like this so I can more visually see the difference between me healthy (exercise, floss e.t.c.) tracks and the bad ones (take out, soda e.t.c).

**Comment by lordi** [comment]
Support for colors is currently worked on in branch ``feature-colored-ticks``.
It is currently sheduled to be released in 1.4.0

**Comment by lordi** [comment]
Support for colors merged in e56ccdcb60ee2261d74d8143ddde16720337eed1 
It still needs some work but will appear in the next version.
