### ISSUE TITLE
[Feature] Larger text box for description of tracks or scroll support

### ISSUE THREAD

**Issue by gottalovebrando** [lordi/tickmate#40]
It would be great if the program would allow more space in the track details screen to view what I have written. I need more space for the name of the track AND the description (See screen shots). Personally, support to display up to 700 characters (including spaces) for the description would be nice. Great app! Ben Franklin actually implemented a journal much like this in a good old fashioned paper journal long before we had fancy things such as android.

![screenshot_2015-02-21-11-17-08](https://cloud.githubusercontent.com/assets/11136547/6314840/221dd3cc-b9bc-11e4-9b00-582ffccfce02.png)
![screenshot_2015-02-21-11-17-22](https://cloud.githubusercontent.com/assets/11136547/6314841/222d3c18-b9bc-11e4-9ab7-aecaba81b5bd.png)

**Comment by lordi** [comment]
Yea, this will be fixed.
About Ben Franklin, thats interesting, do you happen to know what categories/"tracks" he proposed?

**Comment by gottalovebrando** [comment]
Oh you're awesome! Do you have any idea on an ETA? I would fix the problem myself but I don't want to break anything. I have very limited experience with git, some java experience and no experience developing android apps (although I have the development kit on my computer to run ADB and AVDs). If you think its an easy problem to fix, I'd love the chance to learn and can give a crack at it. What do you think?

As far as Ben Franklin goes, here they are:
1.Temperance-Eat not to dulness, drink not to elevation.
2.Silence-Speak not bu what may benefit others or your self. Avoid trifling conversation.
3.Order-Let all your things have their places. Let each part of your business have its time.
4.Resolution-resolve to perform what you ought. Perform without fail what you resolve.
5.Frugality-Make no expense but to do good to others or yourself: i.e. waste nothing.
6.Industry-Lose no time. Be always employed in something useful. Cut off all unnecessary actions.
7.Sincerity-Use no hurtful deceit. Think innocently and justly; and if you speak; speak accordingly.
8.Justice-Wrong none, by doing injuries or omitting the benefits that are your duty.
9.Moderation-Avoid extremes. Forbear resenting injuries so much as you think they deserve.
10.Cleanliness-Tolerate no uncleanness in body, clothes or habitation.
11.Tranquility-Be not disturbed at trifles, or at accidents common or unavoidable.
12.Chastity-Rarely use venery but for health or offspring; never to dulness, weakness, or the injury of your own or another's peace or reputation.
13.Humility-Imitate Jesus and Socrates.

The autobiography can be a little dry at times but overall, I would highly recommend it. (http://www.amazon.com/dp/B008VQTP8I/)

Citation-Franklin, B., & Masur, L. (2003). The autobiography of Benjamin Franklin: With related documents (2nd ed., pp. 95-96). Boston: Bedford/St. Martin's.

**Comment by lordi** [comment]
Well, it was rather easy to fix: 55b90746af6174ff9332b5f7abeec5c074b18bc6 ;-)

As for his categories, I think its hard to examine all these categories at the end of the day and bring it into the one-bit-system. How, for example would you judge if you had been sincere that day.
I'm closing this ticket, but the diskussion may continue :-)

**Comment by gottalovebrando** [comment]
Oh great! It seemed like that would be a simple thing to implement. Thank you! In the spirit of learning a little how github works (and certainly not wanting to sound impatient), it sounds like someone has to compile the code into an apk and place it in the google play store/f-droid manually? Or can github do that for you automatically at pre-determined times and/or triggers (i.e. automatically compile after a commit with a certain word such as "STABLE" in the comment)?

From my understanding, he would look back on the day and mark all the times he was NOT sincere, frugal, ect. That way, his goal was to actually not have any marks (so our friend Ben would actually need the "multiple occurrences per day" feature I saw you had implemented awhile back). He admits he never reached perfection but that he became a better man because of it. I will also say, some seem a little unimportant while others seem vague but everyone is entitled to their own opinion. I'm sure they made perfect sense to him. I think he wrote those on a 6-7 month sea voyage from England to Philadelphia when he was around 24 yrs old so he certainly had time to think on them.

**Comment by lordi** [comment]
Actually github has nothing to do with compiling the apk and uploading it to f-droid. Github only hosts the git content (it hosts a giant number of projects of which Android apps are only a very small subset), the compiling is done by f-droid itself. All compiling is done automatically.

And you are right, there are "triggers" that define a new version. For this, f-droid uses git tags. You can call `git tag` on the command line or go to https://github.com/lordi/tickmate/releases to see all of Tickmate's tags.
