### ISSUE TITLE
[bug] Doesn't automatically change to current day on open

### ISSUE THREAD

**Issue by yjftsjthsd-g** [lordi/tickmate#42]
In version 1.2.2 on Android 5.1.1, I will often open the app and it will still show yesterday as today and not move display today's row unless I use the "Jump to today" menu option. If I use said menu option to show the bottom row, yesterday is still shown as "today" (see screenshot).
![screenshot_2015-05-14-14-55-29](https://cloud.githubusercontent.com/assets/7230787/7639394/85f60fcc-fa49-11e4-8431-691339af2618.png)

**Comment by lordi** [comment]
Thanks for the report, I'll try to reproduce...

**Comment by lordi** [comment]
This is probably solved with 62ce899f400c15568ee267b996287bcb7f0990fa, to appear in the next version.

**Comment by lordi** [comment]
I'll close this as it is probably fixed in the next release, if not, please re-open.

**Comment by grrrrr** [comment]
@lordi I am seeing it opening a week behind the current date with version `1.2.3`

**Comment by lordi** [comment]
Hi, thanks for the report. Can you give more details?

- What language do you use?
- Did you change the date order in settings?
- Does it happen _everytime_ when you open Tickmate?

**Comment by grrrrr** [comment]
* OS = CyanogenMod 11
* Language = english
* Date order = descending 
* Happens = not every time.  The only reproducable way I can do it is if  I reboot or  swipe tickmate off the list of running apps after long pressing home key.    I have seen it more commonly happening with no interaction and no restarts but can not reproduce.  The first time I tested the swipe was for this post.
