### ISSUE TITLE
Bug when deleting or disabling tracks

### ISSUE THREAD

**Issue by Ezelty** [lordi/tickmate#45]
I noticed a bug that happens when I delete or disable a track: whereas the track is deleted/disabled and cannot be ticked anymore, the icon is still shown (so there are more columns than icons, see the screenshot at the end of my message). I have to quit and open the app again, or go to the track list and then go back to the main screen, to have the icons and the columns matching. When I click on the icon of a track I deleted, the app crashes.
At first I had the same bug when I created new tracks: I could tick the new track but I couldn't see the icon. Strangely, I don't have any problem anymore when I create new tracks.
I know this bug is not very important but I thought I could report it anyway.

I tested with the versions 1.2.2 and 1.2.1, and the bug is present only in the version 1.2.2. I couldn't try with 1.2.0 as the app crashed each time I tried to add a track. I use Android 4.4.4.
![screenshot_2015-06-05-16-37-10](https://cloud.githubusercontent.com/assets/12199874/8008838/e2e46690-0ba4-11e5-8886-123adef8b12a.png)

**Comment by lordi** [comment]
Should be fixed with 62ce899f400c15568ee267b996287bcb7f0990fa (upcoming version)

**Comment by lordi** [comment]
I'll close this as it is probably fixed in the next version. If the problem persists, please re-open.
