### ISSUE TITLE
Month encoding in database

### ISSUE THREAD

**Issue by AlexandreRio** [lordi/tickmate#53]
Hi,

I noticed that tickmate use Calendar.MONTH to determine the current month, which starts with 0 for January while the day and the year start with 1.

This is a bit confusing when you export your data for analysis.

I know this can only be changed for new databases and is only useful for aesthetics export since it's the Java API encoding.

This is just a suggestion, what do you think?

**Comment by lordi** [comment]
I think this should just be adjusted in your data analysis script, because changing the database semantic now is error-prone. But you are right, I stumbled over that one, too. Seems like Java API does not like consistency :disappointed: 
What tools do you use to analyze the data?

**Comment by AlexandreRio** [comment]
I was only looking at data but I may use [csvkit](http://csvkit.readthedocs.org/en/0.9.1/) for quick data manipulation or R to get correlation between my tracks or maybe even [plotly](https://plot.ly) for beautiful graphs.

I don't know what other people use to compute basic information like discussed in #17
