### ISSUE TITLE
App opens with the last week

### ISSUE THREAD

**Issue by andunix** [lordi/tickmate#59]
When I open the app, it shows the richt day of week, but from the last week. So I always have to scroll 7 days to the top after opening the app.

**Comment by lordi** [comment]
Does it happen every day and every time you open the app or only under certain conditions?

**Comment by andunix** [comment]
It happens every time the app is started. When I come back after a short time and the app was still persistent in the RAM, it's at the last position.

**Comment by lordi** [comment]
Did you choose ascending or descending date order? Does it also happen with the latest version 1.3.0 (released today)?

**Comment by andunix** [comment]
It's fixed in 1.3.0. Thanks!
