### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 1.3.1.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [lordi/tickmate#69]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 1.3.1.

**Comment by lordi** [comment]
Thanks I'll try to get it in there

**Comment by locutis-of-borg-1999** [comment]
:-)

**Comment by lordi** [comment]
It is included now: https://f-droid.org/repository/browse/?fdfilter=tickmate&fdid=de.smasi.tickmate
