### ISSUE TITLE
Restore last used tick-group on restart

### ISSUE THREAD

**Issue by k3b** [lordi/tickmate#70]
Tickmate always starts with the the tickgroup "all".

I would prefer to see the last used tickgroup when i (re-) start the app.

**Comment by bitwave** [comment]
@k3b or let the the user decide and set the startup group explicit.

**Comment by lordi** [comment]
I'd vote for starting with the last opened group (because this also is the behaviour when Tickmate is resumed) with an additional setting to turn this behaviour of.
