### ISSUE TITLE
app crashes on start

### ISSUE THREAD

**Issue by aberlin** [lordi/tickmate#77]
The app crashes on start. 
Hope this helps: https://gist.github.com/aberlin/b528697a39d0a56251fd781872edb6b9

Worked with older versions error due to v 1.4.0

**Comment by Asara** [comment]
The instant you add a single track and go back, the app crashes out.  If you have no tracks the app starts up.  Installed it for the first time via F-Droid

**Comment by lordi** [comment]
Whops, this happened for API level < 21. Fixed now in v1.4.1.
