### ISSUE TITLE
Add "longest streak" to detail page

### ISSUE THREAD

**Issue by craftyguy** [lordi/tickmate#78]
It would be great to have a "longest streak" printed in the detail page for each item in the journal. This field would capture the longest you have 'ticked' an item in a row (consecutive days).

**Comment by lordi** [comment]
Thanks very much, but I'll close this as it is the same as #32

**Comment by craftyguy** [comment]
Ah, sorry about that, guess I didn't do a great job searching before submitting this. Thank you for the terrific app!
