### ISSUE TITLE
Add instructions in an obvious place (e.g., README)

### ISSUE THREAD

**Issue by aleksejrs** [lordi/tickmate#80]
I can't rediscover how to decrease the number.

**Comment by lordi** [comment]
Added the description directly to the preference:

![2016-05-16_357x73](https://cloud.githubusercontent.com/assets/232086/15295779/6aed5e2c-1b92-11e6-9342-e5094bb38175.png)

**Comment by aleksejrs** [comment]
Thanks.  It was very confusing being unaccustomed to touch screen when long presses seemed to switch the direction randomly (they still do, but now I know when it's the wrong one).
