### ISSUE TITLE
Export/import instruction is not clear

### ISSUE THREAD

**Issue by rozie** [lordi/tickmate#84]
I tried to move DB to another device. I could change the name of the backup (export) but there's no way to choose directory, and even no info where DB was exproted exactly.

The same with import - no way to choose directory.

Giving information about directories or allowing to choose them would make backup/restore a lot easier.

**Comment by lordi** [comment]
The import/export directory is printed on the "About" page. Does this help?

**Comment by rozie** [comment]
Information is OK, but I believe it should be moved to a screen with import/export dialog, as it belongs there.

**Comment by lordi** [comment]
Added in to the dialogs. In the case of the import dialog, it is only printed when no backups are found.
