### ISSUE TITLE
Enter a number by longpressing a box

### ISSUE THREAD

**Issue by Ezelty** [lordi/tickmate#86]
Instead of removing the last tick, could a long press open a field that allows the user to directly enter the number? We would still be able to remove the last tick, and in addition we could enter high numbers without having to press the box so many times.
It's not an important feature, but I think it could be a nice one. Thank you!

**Comment by lordi** [comment]
Thanks for the suggestions. I think it makes sense. Unfortunately my time that I have for Tickmate development is currently limited.

**Comment by Ezelty** [comment]
Thanks for your answer! No problem, I understand. I'm not able to do it myself, sorry.
